// Jain Cosmological and Astrological Framework
//
// Sources (see references/sources.md):
//  - Panch Samvay (Five-fold Causality): Tattvarthasutra ch. 5 + Research Report §1.
//  - Planetary → karma mapping: Research Report §1 (karma-graha table).
//    [REQUIRES_RESEARCH] verse-level OCR from Bhadrabahu Samhita pending.
//  - Jain sidereal geometry: Surya Prajnapti (SP-1) + Jambudvipa Prajnapti (JP-1);
//    distilled in Research Report §3-§4.
//  - 28 nakshatra model with unequal muhurta spans: SP-1 ch. 3;
//    Research Report §4 (Sidereal Geometry table).
//  - Bhadrabahu Samhita transit rules: BDS-1; Research Report §5.
//    [REQUIRES_RESEARCH] full BDS-1 OCR pending.

// ─── Panch Samvay (Five-fold Causality Matrix) ───────────────────────────────
// Governs all worldly occurrences through interaction of five vectors.
// Source: Tattvarthasutra ch. 5 + Research Report §1.
// The kundali engine treats the first four vectors as a fixed coordinate system;
// Pursharth (free will / sadhana) is the open interface for remedies.
export interface PanchSamvayVector {
  name: string;
  hindiName: string;
  description: string;
  engineRole: string;
}

export const PANCH_SAMVAY: PanchSamvayVector[] = [
  {
    name: 'Kaal',
    hindiName: 'काल',
    description: 'The chronological dimension and temporal coordinates of the cosmos — the current Ara (Pancham Kaal), tithi, nakshatra, and dasha period.',
    engineRole: 'Fixed input: birth time, Pancham Kaal factor (1.4×), current panchang state.'
  },
  {
    name: 'Swabhav',
    hindiName: 'स्वभाव',
    description: 'The intrinsic disposition, nature, or natural capacity of the soul — nakshatra nature (param_shubha to ashubha), gunasthana level.',
    engineRole: 'Fixed input: nakshatra nature classification, birth karma type.'
  },
  {
    name: 'Purakrit',
    hindiName: 'पूरकृत',
    description: 'Specific feedback loops generated by past karmic acquisitions — the 8 karmas in their current Udaya/Satta/Nirjara state.',
    engineRole: 'Fixed input: dominant karma, karma intensity scores from KarmaEngine.'
  },
  {
    name: 'Niyati',
    hindiName: 'नियति',
    description: 'The inevitable progression of cosmological and material laws — planetary positions at birth, dasha sequences, cosmic time cycles.',
    engineRole: 'Fixed input: dasha lord, antardasha lord, birth chart coordinates.'
  },
  {
    name: 'Pursharth',
    hindiName: 'पुरुषार्थ',
    description: 'Conscious human exertion and free will — the only dynamic variable capable of neutralizing or mitigating the indicative karmic configuration.',
    engineRole: 'Open interface: sadhana, remedies, vratas, tapasya prescribed by RemedyEngine.'
  }
];

// ─── Planetary → Karma Mapping ────────────────────────────────────────────────
// Maps astrological indicators (Navagraha afflictions, house placements)
// to the 8 Jain karmas they indicate. This is a diagnostic table, NOT a causal
// claim — planets are Nimitta Gyana (indicative science), not causes.
// Source: Research Report §1 (karma-graha table) + [REQUIRES_RESEARCH] BDS-1 verification.
export interface GrahaKarmaMapping {
  graha: string;
  grahaHindi: string;
  indicatedKarma: string;
  karmaHindi: string;
  obscurationFunction: string;
  afflictionIndicator: string;
}

export const GRAHA_KARMA_MAPPINGS: GrahaKarmaMapping[] = [
  {
    graha: 'Mercury',
    grahaHindi: 'बुध',
    indicatedKarma: 'Gyanavaraniya',
    karmaHindi: 'ज्ञानावरणीय',
    obscurationFunction: 'Obscures infinite knowledge (Kevaljnana)',
    afflictionIndicator: 'बुध की पीड़ा — ज्ञानावरणीय कर्म का सूचक; बुद्धि, स्मृति, वाणी में बाधा'
  },
  {
    graha: 'Jupiter',
    grahaHindi: 'बृहस्पति',
    indicatedKarma: 'Gyanavaraniya',
    karmaHindi: 'ज्ञानावरणीय',
    obscurationFunction: 'Obscures wisdom and teaching (Shrutagyan)',
    afflictionIndicator: 'बृहस्पति की पीड़ा — श्रुत-ज्ञान और गुरु-भक्ति में बाधा का सूचक'
  },
  {
    graha: 'Sun',
    grahaHindi: 'सूर्य',
    indicatedKarma: 'Darshanavaraniya',
    karmaHindi: 'दर्शनावरणीय',
    obscurationFunction: 'Obscures infinite perception (Kevaldarshana) — primary luminary of consciousness',
    afflictionIndicator: 'सूर्य की पीड़ा — दर्शनावरणीय कर्म, सम्यग्-दृष्टि में अस्थिरता का सूचक'
  },
  {
    graha: 'Moon',
    grahaHindi: 'चन्द्र',
    indicatedKarma: 'Darshanavaraniya',
    karmaHindi: 'दर्शनावरणीय',
    obscurationFunction: 'Obscures perception — secondary luminary, also governs Vedaniya (pleasure/pain)',
    afflictionIndicator: 'चन्द्र की पीड़ा — दर्शन-बाधा और वेदनीय (सुख-दुःख) दोनों का सूचक'
  },
  {
    graha: 'Venus',
    grahaHindi: 'शुक्र',
    indicatedKarma: 'Mohaniya',
    karmaHindi: 'मोहनीय',
    obscurationFunction: 'Governs emotional and relational drives under Mohaniya',
    afflictionIndicator: 'शुक्र की पीड़ा — मोहनीय कर्म (कषाय, आसक्ति, वैवाहिक कलह) का सूचक'
  },
  {
    graha: 'Mars',
    grahaHindi: 'मंगल',
    indicatedKarma: 'Mohaniya',
    karmaHindi: 'मोहनीय',
    obscurationFunction: 'Governs physical drives and passions (Charitra Mohaniya)',
    afflictionIndicator: 'मंगल की पीड़ा — चारित्र-मोहनीय, क्रोध-कषाय का तीव्र सूचक'
  },
  {
    graha: 'Saturn',
    grahaHindi: 'शनि',
    indicatedKarma: 'Antaraya',
    karmaHindi: 'अंतराय',
    obscurationFunction: 'Obscures infinite energy (Anantshakti), creating obstacles to achievement',
    afflictionIndicator: 'शनि की पीड़ा — अंतराय कर्म (लाभ-दान-भोग-उपभोग-वीर्य-अंतराय) का सूचक'
  },
  {
    graha: 'Moon (Transit)',
    grahaHindi: 'चन्द्र (गोचर)',
    indicatedKarma: 'Vedaniya',
    karmaHindi: 'वेदनीय',
    obscurationFunction: 'Generates sensory experiences of physical pleasure and pain',
    afflictionIndicator: 'गोचर चन्द्र — वेदनीय कर्म के उदय-काल का सूचक; सुख-दुःख का ज्वार'
  },
  {
    graha: 'Ascendant (Lagna)',
    grahaHindi: 'लग्न',
    indicatedKarma: 'Naam',
    karmaHindi: 'नाम',
    obscurationFunction: 'Determines physical form, bodily structure, and sensory organs',
    afflictionIndicator: 'लग्न-दुर्बलता — नाम कर्म का शरीर-रचना पक्ष, रूप-सम्बन्धी चिंताओं का सूचक'
  },
  {
    graha: 'Sun (9th/10th house)',
    grahaHindi: 'सूर्य (नवम/दशम)',
    indicatedKarma: 'Gotra',
    karmaHindi: 'गोत्र',
    obscurationFunction: 'Dictates environmental circumstances, family lineage, and social status',
    afflictionIndicator: 'नवम-दशम सूर्य-पीड़ा — गोत्र कर्म, कुल-प्रतिष्ठा और सामाजिक स्थान का सूचक'
  },
  {
    graha: 'Saturn (longevity)',
    grahaHindi: 'शनि (आयु-कारक)',
    indicatedKarma: 'Ayushya',
    karmaHindi: 'आयुष्य',
    obscurationFunction: 'Defines the exact chronological life span of the current incarnation',
    afflictionIndicator: 'आयु-कारक शनि की स्थिति — आयुष्य कर्म की दीर्घायु या अल्पायु का सूचक'
  }
];

// ─── Jain Sidereal Geometry — Nakshatra Span Classes ─────────────────────────
// Source: Surya Prajnapti (SP-1) + Jambudvipa Prajnapti (JP-1); Research Report §3-§4.
//
// Key differences from standard 27-nakshatra Vedic model:
// 1. 28 nakshatras — includes Abhijit (α Lyrae)
// 2. Unequal muhurta spans (not equal 13°20')
// 3. Shravana-first ordering (epoch ~500 BCE summer solstice)
// 4. Total zodiacal circumference: exactly 819 + 27/67 muhurtas
//    (= 27 + 21/67 sidereal days × 30 muhurtas/day)
// 5. Summer solstice epoch (vs Vedanga Jyotisha winter solstice)
//
// ARBITRATION (latest extraction supersedes RESEARCH-REPORT-2025 §4):
//   Abhijit span = 9 + 27/67 muhurtas (was 9 + 11/67); four nakshatras were
//   reclassified between span classes — Shatabhisha & Jyeshtha: short→standard(30);
//   Purva Phalguni & Hasta: standard→short(15). Both old and new tables close to
//   their own totals; the new allocation (270 + 450 + 90 + 9·27/67) is adopted as
//   authoritative per user directive on source precedence.
//
// Verification: (1 × 9 + 27/67) + (6 × 15) + (6 × 45) + (15 × 30) = 819 + 27/67 ✓

export const JAIN_ZODIAC_TOTAL_MUHURTAS = 819 + 27 / 67; // ≈ 819.402985

export type NakshatraSpanClass = 'abhijit' | 'short_span' | 'long_span' | 'standard_span';

export interface JainNakshatraSpan {
  name: string;
  spanClass: NakshatraSpanClass;
  zodiacStretchMuhurtas: number;
  solarConjunctionDays: number;
  solarConjunctionMuhurtas: number;
}

// Shravana-first ordering per SP-1 (epoch ~500 BCE).
// Source: Research Report §4 + SP-1 ch.3; class memberships per latest arbitration.
export const JAIN_NAKSHATRAS_ORDERED: JainNakshatraSpan[] = [
  { name: 'Shravana',          spanClass: 'standard_span', zodiacStretchMuhurtas: 30, solarConjunctionDays: 13, solarConjunctionMuhurtas: 12 },
  { name: 'Dhanistha',         spanClass: 'standard_span', zodiacStretchMuhurtas: 30, solarConjunctionDays: 13, solarConjunctionMuhurtas: 12 },
  { name: 'Satabhisha',        spanClass: 'standard_span', zodiacStretchMuhurtas: 30, solarConjunctionDays: 13, solarConjunctionMuhurtas: 12 },
  { name: 'Purvabhadrapada',   spanClass: 'standard_span', zodiacStretchMuhurtas: 30, solarConjunctionDays: 13, solarConjunctionMuhurtas: 12 },
  { name: 'Uttarabhadrapada',  spanClass: 'long_span',     zodiacStretchMuhurtas: 45, solarConjunctionDays: 20, solarConjunctionMuhurtas: 3  },
  { name: 'Revati',            spanClass: 'standard_span', zodiacStretchMuhurtas: 30, solarConjunctionDays: 13, solarConjunctionMuhurtas: 12 },
  { name: 'Ashwini',           spanClass: 'standard_span', zodiacStretchMuhurtas: 30, solarConjunctionDays: 13, solarConjunctionMuhurtas: 12 },
  { name: 'Bharani',           spanClass: 'short_span',    zodiacStretchMuhurtas: 15, solarConjunctionDays: 6,  solarConjunctionMuhurtas: 21 },
  { name: 'Krittika',          spanClass: 'standard_span', zodiacStretchMuhurtas: 30, solarConjunctionDays: 13, solarConjunctionMuhurtas: 12 },
  { name: 'Rohini',            spanClass: 'long_span',     zodiacStretchMuhurtas: 45, solarConjunctionDays: 20, solarConjunctionMuhurtas: 3  },
  { name: 'Mrigashira',        spanClass: 'standard_span', zodiacStretchMuhurtas: 30, solarConjunctionDays: 13, solarConjunctionMuhurtas: 12 },
  { name: 'Ardra',             spanClass: 'short_span',    zodiacStretchMuhurtas: 15, solarConjunctionDays: 6,  solarConjunctionMuhurtas: 21 },
  { name: 'Punarvasu',         spanClass: 'long_span',     zodiacStretchMuhurtas: 45, solarConjunctionDays: 20, solarConjunctionMuhurtas: 3  },
  { name: 'Pushya',            spanClass: 'standard_span', zodiacStretchMuhurtas: 30, solarConjunctionDays: 13, solarConjunctionMuhurtas: 12 },
  { name: 'Aslesha',           spanClass: 'short_span',    zodiacStretchMuhurtas: 15, solarConjunctionDays: 6,  solarConjunctionMuhurtas: 21 },
  { name: 'Magha',             spanClass: 'standard_span', zodiacStretchMuhurtas: 30, solarConjunctionDays: 13, solarConjunctionMuhurtas: 12 },
  { name: 'Purvaphalguni',     spanClass: 'short_span',    zodiacStretchMuhurtas: 15, solarConjunctionDays: 6,  solarConjunctionMuhurtas: 21 },
  { name: 'Uttaraphalguni',    spanClass: 'long_span',     zodiacStretchMuhurtas: 45, solarConjunctionDays: 20, solarConjunctionMuhurtas: 3  },
  { name: 'Hasta',             spanClass: 'short_span',    zodiacStretchMuhurtas: 15, solarConjunctionDays: 6,  solarConjunctionMuhurtas: 21 },
  { name: 'Chitra',            spanClass: 'standard_span', zodiacStretchMuhurtas: 30, solarConjunctionDays: 13, solarConjunctionMuhurtas: 12 },
  { name: 'Svati',             spanClass: 'short_span',    zodiacStretchMuhurtas: 15, solarConjunctionDays: 6,  solarConjunctionMuhurtas: 21 },
  { name: 'Vishakha',          spanClass: 'long_span',     zodiacStretchMuhurtas: 45, solarConjunctionDays: 20, solarConjunctionMuhurtas: 3  },
  { name: 'Anuradha',          spanClass: 'standard_span', zodiacStretchMuhurtas: 30, solarConjunctionDays: 13, solarConjunctionMuhurtas: 12 },
  { name: 'Jyestha',           spanClass: 'standard_span', zodiacStretchMuhurtas: 30, solarConjunctionDays: 13, solarConjunctionMuhurtas: 12 },
  { name: 'Mula',              spanClass: 'standard_span', zodiacStretchMuhurtas: 30, solarConjunctionDays: 13, solarConjunctionMuhurtas: 12 },
  { name: 'Poorvashadha',      spanClass: 'standard_span', zodiacStretchMuhurtas: 30, solarConjunctionDays: 13, solarConjunctionMuhurtas: 12 },
  { name: 'Uttarashadha',      spanClass: 'long_span',     zodiacStretchMuhurtas: 45, solarConjunctionDays: 20, solarConjunctionMuhurtas: 3  },
  { name: 'Abhijit',           spanClass: 'abhijit',       zodiacStretchMuhurtas: 9 + 27 / 67, solarConjunctionDays: 4, solarConjunctionMuhurtas: 6 }
];

// Verify zodiac closure: sum of all spans = 819 + 27/67 ✓
// (1 × (9 + 27/67)) + (6 × 15) + (6 × 45) + (15 × 30) = 819.403

// ─── Jyotish-Loka belt & Vimana metrics (GS.5) ───────────────────────────────
// Source: GAP_CLOSING_RESEARCH GS.5 (SP/TP corpus) — VERIFIED.
// The Jyotish Chakra belt resides strictly between 790 and 900 yojanas above the
// Madhya Loka plane (thickness exactly 110 yojanas).
export const JYOTISH_LOKA_BELT = {
  minYojaans: 790,
  maxYojaans: 900,
  thicknessYojaans: 110,
  bodies: [
    { key: 'tara',      hindiName: 'तारागण',   heightYojaans: 790 },
    { key: 'surya',     hindiName: 'सूर्य',     heightYojaans: 800 },
    { key: 'chandra',   hindiName: 'चन्द्र',    heightYojaans: 880 },
    { key: 'nakshatra', hindiName: 'नक्षत्र',   heightYojaans: 884 },
    // Grahas scale progressively 888 → 900 (Budha 888, Shukra 891, Guru 894, Mangal 897, Shani 900).
    { key: 'grahas',    hindiName: 'ग्रह (८८८–९००)', heightYojaans: 888 }
  ] as const
};

// Vimana diameters (exact fractions of a yojana).
export const VIMANA_DIAMETERS_YOJANA = {
  surya: 48 / 61,
  chandra: 56 / 61
};

// Path-wise day/night lengths in muhurtas (GS.5).
// FINAL ARBITRATION (ultimate-blueprint resolution): the Sun is on the
// INNERMOST Mandala at the SUMMER solstice (longest day = 18 muhurtas) and on
// the OUTERMOST Mandala at the WINTER solstice (shortest day = 12). Equinoxes
// = 15/15. This supersedes every earlier path-direction reading.
export const SOLSTICE_DAY_NIGHT_MUHURTAS = {
  summerSolsticeInnermostPath: { day: 18, night: 12 },
  winterSolsticeOutermostPath: { day: 12, night: 18 },
  equinoxes:               { day: 15, night: 15 }
} as const;

// ─── Solar Mandala progression (v3 §A / final ruling) ────────────────────────
// 184 concentric paths; half-transit inner↔outer takes exactly 183 days.
// Day-length change per daily path shift Δ = (18−12)/183 = 2/61 muhurta
// ≈ 1 minute 34.4 seconds per day.
export const MANDALA_PATH_PROGRESSION = {
  totalPaths: 184,
  halfTransitDays: 183,
  dayLengthDeltaMuhurtasPerPath: 2 / 61,
  dayLengthDeltaSecondsPerDay: (2 / 61) * 48 * 60 // ≈ 94.4 s
} as const;

// ─── Moon-revolution / bhabhog arithmetic (final micro-residual) ─────────────
// A yuga holds exactly 67 sidereal lunar months; one sidereal month =
// 27 + 21/67 days = 819 + 27/67 muhurtas. Per-orbit bhabhog parts of 67:
export const MOON_SIDEREAL_MONTH_DAYS = 27 + 21 / 67;
export const MOON_BHABHOG_PARTS_OF_67 = {
  mahatStars:   { count: 6,  muhurtasEach: 45,           partsOf67Each: 45 * 67 },          // 3015
  samaStars:    { count: 15, muhurtasEach: 30,           partsOf67Each: 30 * 67 },          // 2010
  kanishthaStars:{ count: 6, muhurtasEach: 15,           partsOf67Each: 15 * 67 },          // 1005
  abhijit:      { count: 1,  muhurtasExact: '9 + 27/67', partsOf67Total: (9 * 67 + 27) }    // 630
} as const;

// ─── Spatial unit conversions (final micro-residual) ─────────────────────────
export const YOJANA_CONVERSIONS = {
  vyavaharaYojanaKmRange: [12.8, 14.4] as const,
  vyavaharaYojanaMilesRange: [8.0, 9.0] as const,
  pramanaYojanaInVyavaharaYojanas: 500,
  pramanaYojanaKmRange: [6400, 7200] as const,
  rajjuMeters: 1.45e21
} as const;

// ─── Jyotishi-Dev vitals (final micro-residual) ──────────────────────────────
export const JYOTISHI_DEV_VITALS = {
  ayu: {
    chandra:    { maxHindi: '१ पल्योपम + १,००,००० वर्ष', minHindi: '१/४ पल्योपम' },
    surya:      { maxHindi: '१ पल्योपम',                 minHindi: '१/४ पल्योपम' },
    nakshatras: { maxHindi: '१/२ पल्योपम',               minHindi: '१/४ पल्योपम' },
    taras:      { maxHindi: '१/४ पल्योपम',               minHindi: '१/८ पल्योपम' }
  },
  ucchvasaIntervalMuhurtas: 4,   // breath once every ~4 muhurtas
  aharIntervalDays: 4            // mānasik āhar once every ~4 days
} as const;

// ─── Coordinate Transformation: Standard Longitude → Jain Zodiac ─────────────
// Transforms standard sidereal longitude (0-360°) into the graduated Jain zodiac
// representation of 819.164179 muhurtas based on unequal nakshatra classes.
// Source: Research Report §4 + SP-1.

export interface JainZodiacProjection {
  graduatedMuhurtas: number;
  activeNakshatra: string;
  balanceWithinNakshatraMuhurtas: number;
  spanClass: NakshatraSpanClass;
}

export function calculateJainZodiacProjection(standardLongitude: number): JainZodiacProjection {
  const gradMuhurtas = (((standardLongitude % 360) + 360) % 360 / 360.0) * JAIN_ZODIAC_TOTAL_MUHURTAS;

  let accumulated = 0.0;
  for (const n of JAIN_NAKSHATRAS_ORDERED) {
    const end = accumulated + n.zodiacStretchMuhurtas;
    if (gradMuhurtas >= accumulated && gradMuhurtas < end) {
      return {
        graduatedMuhurtas: gradMuhurtas,
        activeNakshatra: n.name,
        balanceWithinNakshatraMuhurtas: end - gradMuhurtas,
        spanClass: n.spanClass
      };
    }
    accumulated = end;
  }
  // Wrap: last nakshatra (Abhijit)
  const last = JAIN_NAKSHATRAS_ORDERED[JAIN_NAKSHATRAS_ORDERED.length - 1];
  return {
    graduatedMuhurtas: gradMuhurtas,
    activeNakshatra: last.name,
    balanceWithinNakshatraMuhurtas: 0,
    spanClass: last.spanClass
  };
}

// ─── Ishtakaal Calculation ────────────────────────────────────────────────────
// Elapsed time between the APPARENT astronomical sunrise and the precise birth
// moment (umbilical cord severance).
// Source: PARITY-REPORT-2026 §"Precise Ishtakaal Conversion" (primary; supersedes
// the earlier RESEARCH-REPORT-2025 Ucchvasa/Stoka/Lava hierarchy).
//
// Unit hierarchy (PARITY-REPORT-2026):
//  - 1 solar day = 24 hours = 60 Ghatis (Nālikās)
//  - 1 Ghati  = 24 minutes = 60 Palas (Vighatis)
//  - 1 Pala   = 24 seconds = 60 Vipalas (Prāṇas)
//  - 1 Vipala = 0.4 seconds = 1 Prāṇa
//  - 1 Prāṇa  = 7 Stokas
//  - 1 Stoka  = 7 Lavas
//  - 1 Lava   = innumerable Āvalis
//
// Formulas:
//  Ghatis  = ⌊Ishtakaal(hours) × 2.5⌋
//  Palas   = ⌊(Ishtakaal × 2.5 − Ghatis) × 60⌋
//  Vipalas = ⌊((Ishtakaal × 2.5 − Ghatis) × 60 − Palas) × 60⌋

export interface IshtakaalResult {
  ghatis: number;
  palas: number;
  vipalas: number;
  equivalentMuhurtas: number;
  microState: {
    // Sub-Vipala breakdown: 1 Vipala (Prāṇa) = 7 Stokas; 1 Stoka = 7 Lavas.
    // Source: PARITY-REPORT-2026 (Stoka > Lava — inverts RESEARCH-REPORT-2025).
    stokas: number;
    lavas: number;
  };
  formatted: string;
}

export function calculateIshtakaal(
  birthTimeHHMM: string,
  sunriseTimeHHMM: string
): IshtakaalResult {
  function toDecimalHours(hhmm: string): number {
    const parts = hhmm.split(':').map(Number);
    return (parts[0] || 0) + (parts[1] || 0) / 60 + (parts[2] || 0) / 3600;
  }

  const birthH = toDecimalHours(birthTimeHHMM);
  const sunriseH = toDecimalHours(sunriseTimeHHMM || '06:00');

  // Birth before sunrise belongs to the preceding astronomical day.
  // Source: PARITY-REPORT-2026 Ishtakaal case split.
  const deltaT = birthH >= sunriseH ? birthH - sunriseH : (birthH + 24) - sunriseH;

  const ishtakaalGhatis = deltaT * 2.5;
  const G = Math.floor(ishtakaalGhatis);
  const P = Math.floor((ishtakaalGhatis - G) * 60);
  const V = Math.floor(((ishtakaalGhatis - G) * 60 - P) * 60);
  const equivalentMuhurtas = ishtakaalGhatis / 2;

  // Sub-Vipala: fractional Vipala → Stokas (×7) → Lavas (×7).
  const vipalaFrac = ((ishtakaalGhatis - G) * 60 - P) * 60 - V;
  const stokas = Math.floor(vipalaFrac * 7);
  const lavas = Math.floor((vipalaFrac * 7 - stokas) * 7);

  return {
    ghatis: G,
    palas: P,
    vipalas: V,
    equivalentMuhurtas: Math.round(equivalentMuhurtas * 100) / 100,
    microState: { stokas, lavas },
    formatted: `${G} घटी ${P} पल ${V} विपल (${Math.round(equivalentMuhurtas * 10) / 10} मुहूर्त)`
  };
}

// ─── Bhadrabahu Samhita: Venus Mandala System ─────────────────────────────────
// Three Mandalas (vessels) — planets change effects when crossing them.
// Source: GAP_CLOSING_RESEARCH GG.4 (blueprint §A.4) — supersedes the earlier
// six-mandala RESEARCH-REPORT-2025 stub, which was flagged [REQUIRES_RESEARCH].
export interface VenusMandala {
  id: number;
  name: string;
  hindiName: string;
  nakshatras: string[];
  indicator: string;
  indicatorHindi: string;
}

export const VENUS_MANDALAS: VenusMandala[] = [
  {
    id: 1, name: 'Abhyantara', hindiName: 'अभ्यंतर मंडल (आंतरिक)',
    nakshatras: ['Krittika', 'Rohini', 'Mrigashira', 'Ardra', 'Punarvasu', 'Pushya'],
    indicator: 'High spiritual potency, stable rainfall',
    indicatorHindi: 'उच्च आध्यात्मिक सामर्थ्य, स्थिर वर्षा'
  },
  {
    id: 2, name: 'Madhyama', hindiName: 'मध्यम मंडल',
    nakshatras: ['Ashlesha', 'Magha', 'Purva Phalguni', 'Uttara Phalguni', 'Hasta', 'Chitra'],
    indicator: 'Worldly development, political transitions',
    indicatorHindi: 'लौकिक विकास, राजनीतिक परिवर्तन'
  },
  {
    id: 3, name: 'Bahya', hindiName: 'बाह्य मंडल',
    nakshatras: ['Svati', 'Vishakha', 'Anuradha', 'Jyeshtha', 'Mula', 'Purvashadha', 'Uttarashadha'],
    indicator: 'Worldly upheavals, droughts, market volatility',
    indicatorHindi: 'सांसारिक उथल-पुथल, अकाल, बाज़ार-अस्थिरता'
  }
];

export function getVenusMandalaForNakshatra(nakshatraName: string): VenusMandala | undefined {
  return VENUS_MANDALAS.find(m => m.nakshatras.includes(nakshatraName));
}

// ─── Gochara base-house table (GG.4) ─────────────────────────────────────────
// Auspicious transit houses counted from the natal Moon sign.
// Source: GAP_CLOSING_RESEARCH GG.4 (blueprint §A.4) — first Agamic-grounded
// gochara baseline; per-graha vedha rules remain [REQUIRES_RESEARCH] (BDS-1 OCR).
export const GOCHARA_AUSPICIOUS_HOUSES: Record<string, number[]> = {
  Sun:    [3, 6, 10, 11],
  Moon:   [1, 3, 6, 7, 10, 11],
  Mars:   [3, 6, 11],
  Mercury:[2, 4, 6, 8, 10, 11],
  Jupiter:[2, 5, 7, 9, 11],
  Venus:  [1, 2, 3, 4, 5, 8, 9, 11, 12],
  Saturn: [3, 6, 11]
};

const GOCHARA_GRAHA_HINDI: Record<string, string> = {
  Sun: 'सूर्य', Moon: 'चन्द्र', Mars: 'मंगल', Mercury: 'बुध',
  Jupiter: 'गुरु', Venus: 'शुक्र', Saturn: 'शनि'
};

/** True when a graha transiting `houseFromMoon` (1–12) is auspicious for the native. */
export function isGocharaAuspicious(grahaEn: string, houseFromMoon: number): boolean {
  const houses = GOCHARA_AUSPICIOUS_HOUSES[grahaEn];
  return Array.isArray(houses) && houses.includes(houseFromMoon);
}

export function getGocharaSummary(grahaEn: string, houseFromMoon: number): string {
  const hindi = GOCHARA_GRAHA_HINDI[grahaEn] || grahaEn;
  if (isGocharaAuspicious(grahaEn, houseFromMoon)) {
    return `${hindi} का आपकी चन्द्र-राशि से ${houseFromMoon}वें भाव में गोचर शुभ है।`;
  }
  return `${hindi} का ${houseFromMoon}वें भाव में गोचर साधना-दृष्टि से सावधानी माँगता है — नियमित णमोकार जाप बढ़ाएँ।`;
}

// ─── Bhadrabahu Samhita: Venus Veethi (Orbital Lane) ─────────────────────────
// Three orbital lanes of Venus, each spanning a group of nakshatras.
// Source: Research Report §5. [REQUIRES_RESEARCH] BDS-1 OCR.

export interface VenusVeethi {
  name: string;
  nakshatras: string[];
  indicator: string;
}

export const VENUS_VEETHIS: VenusVeethi[] = [
  {
    name: 'Naagveethi',
    nakshatras: ['Ashwini', 'Bharani', 'Krittika'],
    indicator: 'सर्प-मार्ग — भूकंप, दुर्घटना, जल-परिवहन में संकट का सूचक'
  },
  {
    name: 'Gajveethi',
    nakshatras: ['Rohini', 'Mrigashira', 'Ardra'],
    indicator: 'हस्ति-मार्ग — कृषि-उर्वरता, वर्षा, पशु-पालन में अनुकूलता का सूचक'
  },
  {
    name: 'Airavatveethi',
    nakshatras: ['Punarvasu', 'Pushya', 'Aslesha'],
    indicator: 'ऐरावत-मार्ग — राजनीतिक परिवर्तन, देव-गति बंध का सूचक'
  }
];
